### ISSUE TITLE
Ignore excluded folders

### ISSUE THREAD

**Issue by pavlohrab** [Canna71/obsidian-janitor#2]
Hi, 

Is there an opportunity to implement ignorance of notes, which are in the "excluded" folders? Excluded folders are in Settings -> Files & Links -> Excluded files

**Comment by Canna71** [comment]
For sure, I'll work on it!

**Comment by smaroukis** [comment]
+ 1: I have `code/.c` files that are not used but I like to keep them visible vault structure.

**Comment by Canna71** [comment]
Added in 1.0.1
