### ISSUE TITLE
Show count of items selected beside the total number of orphans

### ISSUE THREAD

**Issue by ManasMadrecha** [Canna71/obsidian-janitor#3]
![image](https://user-images.githubusercontent.com/65993481/190953161-16b933c0-8abb-4f8e-8019-9cb84f27bfbe.png)

Here, when I select some items, it would be better to get a selected count beside the total count, so that on scrolling such a huge list, we know that we have selected some items above as well.

**Comment by Canna71** [comment]
Make sense, thank you for the suggestion. Will do.

**Comment by Canna71** [comment]
Added in 1.0.1
