### ISSUE TITLE
Option to ignore certain attachment types (e.g., PDF)

### ISSUE THREAD

**Issue by ManasMadrecha** [Canna71/obsidian-janitor#4]
It would be nice if the plugin gives an option to ignore certain attachment types which I know that anyway I am never going to link to any md file, so finding them in the orphan list is unnecessary.

**Comment by Canna71** [comment]
Makes sense. Do you think that explicitly ignoring some files would provide a better experience or excluding the whole extension enough?

**Comment by ManasMadrecha** [comment]
Regex might work for both purposes.

Or even glob would be better. 

Similar to the way Obsidian allows files to be ignored for less priority in search.

**Comment by Canna71** [comment]
I am adding a switch to let Janitor ignore files matching Obsidian "Excluded Files". Do you think it's enough or Janitor should have its own exclusion filters?
Thank you for your feedback.

**Comment by ManasMadrecha** [comment]
I think own switch would be more useful.

Because Obsidian's Exclusion list is sort of an archive list for files you no longer need right now, but Janitor's Exclusion list will be for folders currently being operated and for certain attachment types which anyway won't be linked.

For example, I have two-three folders with thousands of pasted images, however I know that dozens of these images are duplicates created inadvertently because I copy+pasted these screenshots successively in hurry while making notes. I don't wish to exclude these folders in Obsidian's Exclusion list or have them not appear in search results. But I would prefer if Janitor has a Regex of its own, so that I can exclude hundreds of PDFs, and docx files of these folders.

**Comment by Canna71** [comment]
Added in 1.0.1
