### ISSUE TITLE
Option to view file when found

### ISSUE THREAD

**Issue by pixelspencil** [Canna71/obsidian-janitor#6]
When running Janitor manually with Ask Confirmation enabled would it be possible to add a 'View file' button at all?

**Comment by Canna71** [comment]
What do you think should happen, the modal closes and the file is opened? Or the file is opened in a new modal?

**Comment by pixelspencil** [comment]
> What do you think should happen, the modal closes and the file is opened? Or the file is opened in a new modal?

Hey @Canna71 thanks for looking - I think it would be better to open the actual file so it takes you to it :)

Thank you!

**Comment by Canna71** [comment]
Added in 1.0.1

**Comment by pixelspencil** [comment]
Hey @Canna71 - I just updated but the plugin is not working as it was prior to update, I tried a test of lowering filesize to 10kb and did a manual scan and it still could not find any files, I know I have files over 10kb for sure - is there something wrong off the back of this update?

**Comment by Canna71** [comment]
Now the plugin by default exclude Obsidian's Excluded Files, maybe your files match those filters? Maybe you could check in the developer tools if you find some errors and report them here?
Thank you.

**Comment by Canna71** [comment]
So the Obsidian Excluded Files are in Settings -> Files & Links -> Excluded Files (at the bottom)
One other thing to look for is the Setting in the Janitor Plugin `Process Big Files`, but it should be enabled by default.
The log you provided was after you forced a scan?

**Comment by pixelspencil** [comment]
Hey!

Yep there is nothing in my excluded files. Process Big Files is also enabled. 

And yep that log was after a manual command, there is another log below - this time no error which is strange.

I also tried running with a prompt and all I got was the little top right alert saying "Janitor scanned and found nothing to clean up"

I'm going to try removing and reinstalling it

Also this loom video may help: https://www.loom.com/share/e294b37ebc294e10a2203c0745d1f2b8

---

Obsidian Developer Console
plugin:obsidian-admonition:479 Obsidian Admonition loaded
main.ts:113 Dataview: version 0.5.46 (requires obsidian 0.13.11)
main.ts:16 Loading Hotkeys++ plugin
main.ts:31 Loading Note Refactor plugin
plugin:obsidian-cloudinary-uploader:2703 loading Cloudinary Uploader
main.ts:17 loading url-into-selection
main.ts:27 Loading vault-statistics Plugin
main.ts:30 loading markdown-table-editor plugin
main.ts:20 loading obsidian-auto-link-title
plugin:media-extended:28 loading media-extended
main.ts:24 loading Sort & Permute lines
app.js:1 Total plugin setup: 684ms
cm-editor-syntax-highlight-obsidian: 156ms
dataview: 98ms
table-editor-obsidian: 89ms
media-extended: 60ms
janitor: 43ms
obsidian-admonition: 42ms
obsidian-hover-editor: 38ms
note-refactor-obsidian: 35ms
templater-obsidian: 22ms
obsidian-style-settings: 16ms
obsidian-vault-statistics-plugin: 10ms
calendar: 9ms
obsidian-cloudinary-uploader: 9ms
workspaces-plus: 9ms
obsidian-sort-and-permute-lines: 8ms
sliding-panes-obsidian: 7ms
obsidian-auto-link-title: 7ms
url-into-selection: 5ms
obsidian-dynamic-toc: 4ms
obsidian-show-file-path: 4ms
better-word-count: 4ms
hotkeysplus-obsidian: 3ms
obsidian-wikipedia: 3ms
obsidian-auto-hide: 3ms
plugin:calendar:998 [Calendar] Failed to find weekly notes folder Error: Failed to find weekly notes folder
    at getAllWeeklyNotes (plugin:calendar:356:15)
    at Object.reindex (plugin:calendar:991:37)
    at getToday (plugin:calendar:3934:15)
    at Object.$$self.$$.update (plugin:calendar:3975:28)
    at init$1 (plugin:calendar:627:8)
    at new Calendar (plugin:calendar:4000:3)
    at CalendarView.onOpen (plugin:calendar:4234:25)
    at CalendarView.<anonymous> (app.js:1:991350)
    at app.js:1:235078
    at Object.next (app.js:1:235183)
index.ts:153 Dataview: all 1077 files have been indexed in 0.84s (1077 cached, 0 skipped).
collect.ts:189 Extras/Templates/TEMPLATE-KANBAN.md: no tokenizer, section.type=comment

**Comment by pixelspencil** [comment]
Tried removing and reinstalling it, still had the same issue.

**Comment by Canna71** [comment]
I guess I have found a bug that caused files not to be scanned if user never touched Obsidian's excluded files options, and the "Ignore Obsidian Excluded Files" was on.
Could you try updating?
Thank you for your patience.

**Comment by pixelspencil** [comment]
Hey,

Ah, awesome so was a weird circumstance in settings that revealed the bug.

I just updated and it's all working again - thank you - it;s a great plugin btw :)
