### ISSUE TITLE
FR: show a toast alert when the scan starts

### ISSUE THREAD

**Issue by luckman212** [Canna71/obsidian-janitor#8]
This is an amazing plug-in. Thank you so much for creating it! @Canna71 

When I first used it, I thought it was broken because I have a large vault and it took around 12 seconds to process it (didn't notice the small message in the status bar...) 

It would be useful if an alert/toast notice was posted when the scan begins.

**Comment by pyrochlore** [comment]
That just happened to me.
An alert would be great for a new user.
Thanks for the plugin!!

**Comment by Canna71** [comment]
Thank you for the feedback. Added notification in next release.
